version: '3.8'

services:
  app:
    build: .
    ports:
      - "5500:5500"
    depends_on:
      - db
    environment:
      - NODE_ENV=production

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"